name: Prompt Bot Deploy CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH orqali serverga ulanish
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/airidev/prompt_bot_project
            
            # Yangi kodni yuklab olish
            git pull origin main
            
            # Virtual muhitdagi pip orqali kutubxonalarni yangilash
            ./venv/bin/pip install -r requirements.txt
            
            # Botni venv ichidagi python orqali restart qilish
            pm2 restart prompt_bot || pm2 start main.py --name "prompt_bot" --interpreter ./venv/bin/python3